import * as path from "path";
import * as vscode from "vscode";

import { checkV05VisualScope, isForbiddenV05Path } from "../../core/v05VisualScopeGuard";
import { ensureDirectory, normalizeWorkspacePath, pathExists, toWorkspaceRelativePath, writeTextFile } from "../../core/workspace";
import { SlotCardStyleConfig, SlotCardStyleValues } from "../../types/visualSurface";

export interface FarmSlotAdapterDetection {
  target: "idle_monster_farm.farm_slots";
  likelyFiles: string[];
  supportedStyleModulePath: string;
  warnings: string[];
}

export interface FarmSlotApplyResult {
  applied: boolean;
  changedFiles: string[];
  warnings: string[];
  blockedFiles: string[];
  likelyFiles: string[];
}

const likelyFarmSlotFiles = [
  "src/scenes/FarmScene.ts",
  "src/ui/FarmSlotView.ts",
  "src/ui/FarmSlotsView.ts",
  "src/ui/FarmGridView.ts",
  "src/rendering/MonsterRenderer.ts",
  "src/config/farmSlotStyle.ts",
  "src/config/farmSlotVisualStyle.ts"
];

export async function detectIdleMonsterFarmFarmSlotAdapter(folder: vscode.WorkspaceFolder): Promise<FarmSlotAdapterDetection> {
  const existingFiles = new Set<string>();
  for (const relativePath of likelyFarmSlotFiles) {
    if (await pathExists(vscode.Uri.joinPath(folder.uri, ...relativePath.split("/")))) {
      existingFiles.add(relativePath);
    }
  }
  for (const relativePath of await findLikelyFarmSlotFiles(folder)) {
    existingFiles.add(relativePath);
  }

  const likelyFiles = Array.from(existingFiles).sort();

  const configPath = await resolveSupportedStyleModulePath(folder);
  const warnings: string[] = [];
  if (likelyFiles.length === 0) {
    warnings.push("No likely Idle Monster Farm farm slot rendering files were detected in this workspace.");
  }
  if (!likelyFiles.some((file) => file.includes("FarmSlot") || file.includes("FarmGrid") || file.includes("farmSlotStyle"))) {
    warnings.push("No dedicated farm slot renderer/style hook was found; v0.5 will apply values to a generated style module only.");
  }

  return {
    target: "idle_monster_farm.farm_slots",
    likelyFiles,
    supportedStyleModulePath: configPath,
    warnings
  };
}

export async function applyIdleMonsterFarmFarmSlotStyle(folder: vscode.WorkspaceFolder, config: SlotCardStyleConfig): Promise<FarmSlotApplyResult> {
  const detection = await detectIdleMonsterFarmFarmSlotAdapter(folder);
  const styleUri = vscode.Uri.joinPath(folder.uri, ...detection.supportedStyleModulePath.split("/"));
  const styleModuleExists = await pathExists(styleUri);
  const changedFiles = [detection.supportedStyleModulePath];
  const scope = checkV05VisualScope(changedFiles, { throughAdapter: true });
  const warnings = [...detection.warnings, ...scope.warnings];

  if (detection.likelyFiles.length === 0 && !styleModuleExists) {
    return {
      applied: false,
      changedFiles: [],
      warnings: [
        ...warnings,
        "Direct apply skipped because this workspace does not look like an Idle Monster Farm target and no supported farm slot style module exists."
      ],
      blockedFiles: [],
      likelyFiles: detection.likelyFiles
    };
  }

  if (!scope.ok) {
    return {
      applied: false,
      changedFiles: [],
      warnings,
      blockedFiles: scope.forbiddenFiles,
      likelyFiles: detection.likelyFiles
    };
  }

  await ensureDirectory(vscode.Uri.file(path.dirname(styleUri.fsPath)));
  await writeTextFile(styleUri, renderFarmSlotStyleModule(config.values));

  return {
    applied: true,
    changedFiles,
    warnings,
    blockedFiles: [],
    likelyFiles: detection.likelyFiles
  };
}

async function resolveSupportedStyleModulePath(folder: vscode.WorkspaceFolder): Promise<string> {
  const candidates = [
    "src/config/farmSlotStyle.ts",
    "src/config/farmSlotVisualStyle.ts"
  ];
  for (const candidate of candidates) {
    if (await pathExists(vscode.Uri.joinPath(folder.uri, ...candidate.split("/")))) {
      return candidate;
    }
  }
  return "src/config/farmSlotStyle.ts";
}

async function findLikelyFarmSlotFiles(folder: vscode.WorkspaceFolder): Promise<string[]> {
  const pattern = new vscode.RelativePattern(folder, "{src,app}/**/*{FarmSlot,FarmSlots,FarmGrid,SlotCard,MonsterRenderer,FarmScene}*.{ts,tsx,js,jsx}");
  const uris = await vscode.workspace.findFiles(pattern, "**/{node_modules,dist,build,out}/**", 50);
  return uris
    .map((uri) => normalizeWorkspacePath(path.relative(folder.uri.fsPath, uri.fsPath)))
    .filter((relativePath) => !isForbiddenV05Path(relativePath));
}

function renderFarmSlotStyleModule(values: SlotCardStyleValues): string {
  return `// Generated by Game Polish Lab v0.5. Visual style values only.
export interface FarmSlotStyle {
  slotWidth: number;
  slotHeight: number;
  gap: number;
  borderWidth: number;
  cornerRadius: number;
  fillColor: string;
  borderColor: string;
  selectedGlowStrength: number;
  lockedOverlayOpacity: number;
  emptySlotOpacity: number;
  mergeCandidatePulseScale: number;
  monsterDisplayScale: number;
  monsterVerticalOffset: number;
}

export const FARM_SLOT_STYLE: FarmSlotStyle = ${JSON.stringify(values, null, 2)};
`;
}

export function summarizeFarmSlotApplyResult(folder: vscode.WorkspaceFolder, result: FarmSlotApplyResult): string[] {
  return [
    `adapter target: idle_monster_farm.farm_slots`,
    `direct apply: ${result.applied ? "applied" : "blocked"}`,
    `changed files: ${result.changedFiles.length > 0 ? result.changedFiles.join(", ") : "none"}`,
    `likely owner/rendering files: ${result.likelyFiles.length > 0 ? result.likelyFiles.join(", ") : "none"}`,
    `workspace: ${toWorkspaceRelativePath(folder, folder.uri)}`,
    ...result.warnings.map((warning) => `warning: ${warning}`),
    ...result.blockedFiles.map((file) => `blocked: ${file}`)
  ];
}
