import { BackgroundReadabilityStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const backgroundRuntimeStylePropertyNames = [
  "backgroundColor",
  "backgroundImageOpacity",
  "contrastOverlayColor",
  "contrastOverlayOpacity",
  "vignetteStrength",
  "patternOpacity",
  "blurAmount",
  "brightness",
  "contrast"
] as const;

export const requiredBackgroundRuntimeProofProperties = [
  "backgroundColor"
] as const;

export function renderBackgroundReadabilityStyleModule(values: BackgroundReadabilityStyleValues): string {
  const runtimePropertyUnion = backgroundRuntimeStylePropertyNames.map((property) => `"${property}"`).join(" | ");
  return `// Generated by Game Polish Lab. Visual style values only.
export interface BackgroundReadabilityStyle {
  backgroundColor: string;
  backgroundImageOpacity: number;
  contrastOverlayColor: string;
  contrastOverlayOpacity: number;
  vignetteStrength: number;
  patternOpacity: number;
  blurAmount: number;
  brightness: number;
  contrast: number;
}

export type BackgroundReadabilityRuntimeLiveStyle = Partial<Pick<BackgroundReadabilityStyle, ${runtimePropertyUnion}>>;

export const DEFAULT_BACKGROUND_READABILITY_STYLE: BackgroundReadabilityStyle = ${JSON.stringify(values, null, 2)};

export const BACKGROUND_READABILITY_STYLE: BackgroundReadabilityStyle = { ...DEFAULT_BACKGROUND_READABILITY_STYLE };

const LIVE_STYLE_PATH = '/.game-polish-lab/live-style/background-readability.json';
const LIVE_POLL_INTERVAL_MS = 300;

let lastLivePayload = '';
let lastLivePollAt = 0;
let livePollInFlight = false;

export async function pollBackgroundReadabilityLiveStyle(now = Date.now()): Promise<boolean> {
  const env = (import.meta as unknown as { env?: { DEV?: boolean } }).env;
  if (!env?.DEV || typeof fetch !== 'function') {
    return false;
  }
  if (livePollInFlight || now - lastLivePollAt < LIVE_POLL_INTERVAL_MS) {
    return false;
  }

  livePollInFlight = true;
  lastLivePollAt = now;
  try {
    const response = await fetch(LIVE_STYLE_PATH, { cache: 'no-store' });
    if (response.status === 404) {
      return applyBackgroundReadabilityStylePayload('');
    }
    if (!response.ok) {
      return false;
    }
    return applyBackgroundReadabilityStylePayload(await response.text());
  } catch {
    return false;
  } finally {
    livePollInFlight = false;
  }
}

function applyBackgroundReadabilityStylePayload(payload: string): boolean {
  if (payload === lastLivePayload) {
    return false;
  }
  lastLivePayload = payload;
  const next = payload ? normalizeLiveBackgroundReadabilityStyle(payload) : DEFAULT_BACKGROUND_READABILITY_STYLE;
  const before = JSON.stringify(BACKGROUND_READABILITY_STYLE);
  Object.assign(BACKGROUND_READABILITY_STYLE, next);
  return JSON.stringify(BACKGROUND_READABILITY_STYLE) !== before;
}

function normalizeLiveBackgroundReadabilityStyle(payload: string): BackgroundReadabilityStyle {
  try {
    const parsed = JSON.parse(payload) as { values?: unknown };
    const source = parsed && typeof parsed === 'object' && parsed.values && typeof parsed.values === 'object'
      ? parsed.values as Record<string, unknown>
      : parsed as Record<string, unknown>;
    return {
      ...DEFAULT_BACKGROUND_READABILITY_STYLE,
      backgroundColor: color(source.backgroundColor, DEFAULT_BACKGROUND_READABILITY_STYLE.backgroundColor),
      backgroundImageOpacity: numberInRange(source.backgroundImageOpacity, DEFAULT_BACKGROUND_READABILITY_STYLE.backgroundImageOpacity, 0, 1),
      contrastOverlayColor: color(source.contrastOverlayColor, DEFAULT_BACKGROUND_READABILITY_STYLE.contrastOverlayColor),
      contrastOverlayOpacity: numberInRange(source.contrastOverlayOpacity, DEFAULT_BACKGROUND_READABILITY_STYLE.contrastOverlayOpacity, 0, 1),
      vignetteStrength: numberInRange(source.vignetteStrength, DEFAULT_BACKGROUND_READABILITY_STYLE.vignetteStrength, 0, 1),
      patternOpacity: numberInRange(source.patternOpacity, DEFAULT_BACKGROUND_READABILITY_STYLE.patternOpacity, 0, 1),
      blurAmount: numberInRange(source.blurAmount, DEFAULT_BACKGROUND_READABILITY_STYLE.blurAmount, 0, 12),
      brightness: numberInRange(source.brightness, DEFAULT_BACKGROUND_READABILITY_STYLE.brightness, 0.4, 1.6),
      contrast: numberInRange(source.contrast, DEFAULT_BACKGROUND_READABILITY_STYLE.contrast, 0.4, 1.8),
    };
  } catch {
    return DEFAULT_BACKGROUND_READABILITY_STYLE;
  }
}

function color(value: unknown, fallback: string): string {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

function numberInRange(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isFinite(value)
    ? Math.min(max, Math.max(min, value))
    : fallback;
}
`;
}

export function matchedBackgroundRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  return Array.from(new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties))).sort();
}

export function missingBackgroundRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set(matchedBackgroundRuntimeProofProperties(proof));
  return requiredBackgroundRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function backgroundRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingBackgroundRuntimeProofProperties(proof).length === 0;
}
