import { BackgroundReadabilityStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const backgroundRuntimeStylePropertyNames = [
  "backgroundColor",
  "backgroundImageOpacity",
  "contrastOverlayColor",
  "contrastOverlayOpacity",
  "vignetteStrength",
  "patternOpacity",
  "blurAmount",
  "brightness",
  "contrast"
] as const;

export const requiredBackgroundRuntimeProofProperties = [
  "backgroundColor"
] as const;

export function renderBackgroundReadabilityStyleModule(values: BackgroundReadabilityStyleValues): string {
  return `// Generated by Game Polish Lab. Visual style values only.
export interface BackgroundReadabilityStyle {
  backgroundColor: string;
  backgroundImageOpacity: number;
  contrastOverlayColor: string;
  contrastOverlayOpacity: number;
  vignetteStrength: number;
  patternOpacity: number;
  blurAmount: number;
  brightness: number;
  contrast: number;
}

export const BACKGROUND_READABILITY_STYLE: BackgroundReadabilityStyle = ${JSON.stringify(values, null, 2)};
`;
}

export function matchedBackgroundRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  return Array.from(new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties))).sort();
}

export function missingBackgroundRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set(matchedBackgroundRuntimeProofProperties(proof));
  return requiredBackgroundRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function backgroundRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingBackgroundRuntimeProofProperties(proof).length === 0;
}
