import { ButtonStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const buttonRuntimeStylePropertyNames = [
  "width",
  "height",
  "fillColor",
  "fillOpacity",
  "borderColor",
  "borderWidth",
  "cornerRadius",
  "labelColor",
  "labelTextSize",
  "iconScale",
  "labelScale",
  "contentGap",
  "paddingX",
  "paddingY",
  "hoverGlowStrength",
  "hoverLift",
  "activePressScale",
  "activePressDurationMs",
  "activeDarkenOpacity",
  "disabledOpacity",
  "disabledSaturation",
  "shadowStrength",
  "glowStrength"
] as const;

export const requiredButtonRuntimeProofProperties = [
  "fillColor",
  "borderColor",
  "labelTextSize"
] as const;

export function renderButtonStyleModule(values: ButtonStyleValues): string {
  return `// Generated by Game Polish Lab. Visual style values only.
export interface ButtonStyle {
  width: number;
  height: number;
  fillColor: string;
  fillOpacity: number;
  borderColor: string;
  borderWidth: number;
  cornerRadius: number;
  labelColor: string;
  labelTextSize: number;
  iconScale: number;
  labelScale: number;
  contentGap: number;
  paddingX: number;
  paddingY: number;
  hoverGlowStrength: number;
  hoverLift: number;
  activePressScale: number;
  activePressDurationMs: number;
  activeDarkenOpacity: number;
  disabledOpacity: number;
  disabledSaturation: number;
  shadowStrength: number;
  glowStrength: number;
}

export const BUTTON_STYLE: ButtonStyle = ${JSON.stringify(values, null, 2)};
`;
}

export function missingButtonRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties));
  return requiredButtonRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function buttonRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingButtonRuntimeProofProperties(proof).length === 0;
}
