import { ButtonStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const buttonRuntimeStylePropertyNames = [
  "width",
  "height",
  "fillColor",
  "fillOpacity",
  "borderColor",
  "borderWidth",
  "cornerRadius",
  "labelColor",
  "labelTextSize",
  "iconScale",
  "labelScale",
  "contentGap",
  "paddingX",
  "paddingY",
  "hoverGlowStrength",
  "hoverLift",
  "activePressScale",
  "activePressDurationMs",
  "activeDarkenOpacity",
  "disabledOpacity",
  "disabledSaturation",
  "shadowStrength",
  "glowStrength"
] as const;

export const requiredButtonRuntimeProofProperties = [
  "fillColor",
  "borderColor",
  "labelTextSize"
] as const;

export function renderButtonStyleModule(values: ButtonStyleValues): string {
  const runtimePropertyUnion = buttonRuntimeStylePropertyNames.map((property) => `"${property}"`).join(" | ");
  return `// Generated by Game Polish Lab. Visual style values only.
export interface ButtonStyle {
  width: number;
  height: number;
  fillColor: string;
  fillOpacity: number;
  borderColor: string;
  borderWidth: number;
  cornerRadius: number;
  labelColor: string;
  labelTextSize: number;
  iconScale: number;
  labelScale: number;
  contentGap: number;
  paddingX: number;
  paddingY: number;
  hoverGlowStrength: number;
  hoverLift: number;
  activePressScale: number;
  activePressDurationMs: number;
  activeDarkenOpacity: number;
  disabledOpacity: number;
  disabledSaturation: number;
  shadowStrength: number;
  glowStrength: number;
}

export type ButtonRuntimeLiveStyle = Partial<Pick<ButtonStyle, ${runtimePropertyUnion}>>;

export const DEFAULT_BUTTON_STYLE: ButtonStyle = ${JSON.stringify(values, null, 2)};

export const BUTTON_STYLE: ButtonStyle = { ...DEFAULT_BUTTON_STYLE };

const LIVE_STYLE_PATH = '/.game-polish-lab/live-style/button.json';
const LIVE_POLL_INTERVAL_MS = 300;

let lastLivePayload = '';
let lastLivePollAt = 0;
let livePollInFlight = false;

export async function pollButtonLiveStyle(now = Date.now()): Promise<boolean> {
  const env = (import.meta as unknown as { env?: { DEV?: boolean } }).env;
  if (!env?.DEV || typeof fetch !== 'function') {
    return false;
  }
  if (livePollInFlight || now - lastLivePollAt < LIVE_POLL_INTERVAL_MS) {
    return false;
  }

  livePollInFlight = true;
  lastLivePollAt = now;
  try {
    const response = await fetch(LIVE_STYLE_PATH, { cache: 'no-store' });
    if (response.status === 404) {
      return applyButtonStylePayload('');
    }
    if (!response.ok) {
      return false;
    }
    return applyButtonStylePayload(await response.text());
  } catch {
    return false;
  } finally {
    livePollInFlight = false;
  }
}

function applyButtonStylePayload(payload: string): boolean {
  if (payload === lastLivePayload) {
    return false;
  }
  lastLivePayload = payload;
  const next = payload ? normalizeLiveButtonStyle(payload) : DEFAULT_BUTTON_STYLE;
  const before = JSON.stringify(BUTTON_STYLE);
  Object.assign(BUTTON_STYLE, next);
  return JSON.stringify(BUTTON_STYLE) !== before;
}

function normalizeLiveButtonStyle(payload: string): ButtonStyle {
  try {
    const parsed = JSON.parse(payload) as { values?: unknown };
    const source = parsed && typeof parsed === 'object' && parsed.values && typeof parsed.values === 'object'
      ? parsed.values as Record<string, unknown>
      : parsed as Record<string, unknown>;
    return {
      ...DEFAULT_BUTTON_STYLE,
      width: numberInRange(source.width, DEFAULT_BUTTON_STYLE.width, 44, 240),
      height: numberInRange(source.height, DEFAULT_BUTTON_STYLE.height, 28, 96),
      fillColor: color(source.fillColor, DEFAULT_BUTTON_STYLE.fillColor),
      fillOpacity: numberInRange(source.fillOpacity, DEFAULT_BUTTON_STYLE.fillOpacity, 0, 1),
      borderColor: color(source.borderColor, DEFAULT_BUTTON_STYLE.borderColor),
      borderWidth: numberInRange(source.borderWidth, DEFAULT_BUTTON_STYLE.borderWidth, 0, 8),
      cornerRadius: numberInRange(source.cornerRadius, DEFAULT_BUTTON_STYLE.cornerRadius, 0, 32),
      labelColor: color(source.labelColor, DEFAULT_BUTTON_STYLE.labelColor),
      labelTextSize: numberInRange(source.labelTextSize, DEFAULT_BUTTON_STYLE.labelTextSize, 8, 32),
      iconScale: numberInRange(source.iconScale, DEFAULT_BUTTON_STYLE.iconScale, 0.4, 2),
      labelScale: numberInRange(source.labelScale, DEFAULT_BUTTON_STYLE.labelScale, 0.4, 2),
      contentGap: numberInRange(source.contentGap, DEFAULT_BUTTON_STYLE.contentGap, 0, 32),
      paddingX: numberInRange(source.paddingX, DEFAULT_BUTTON_STYLE.paddingX, 0, 48),
      paddingY: numberInRange(source.paddingY, DEFAULT_BUTTON_STYLE.paddingY, 0, 36),
      hoverGlowStrength: numberInRange(source.hoverGlowStrength, DEFAULT_BUTTON_STYLE.hoverGlowStrength, 0, 1),
      hoverLift: numberInRange(source.hoverLift, DEFAULT_BUTTON_STYLE.hoverLift, 0, 16),
      activePressScale: numberInRange(source.activePressScale, DEFAULT_BUTTON_STYLE.activePressScale, 0.6, 1.2),
      activePressDurationMs: numberInRange(source.activePressDurationMs, DEFAULT_BUTTON_STYLE.activePressDurationMs, 0, 700),
      activeDarkenOpacity: numberInRange(source.activeDarkenOpacity, DEFAULT_BUTTON_STYLE.activeDarkenOpacity, 0, 1),
      disabledOpacity: numberInRange(source.disabledOpacity, DEFAULT_BUTTON_STYLE.disabledOpacity, 0, 1),
      disabledSaturation: numberInRange(source.disabledSaturation, DEFAULT_BUTTON_STYLE.disabledSaturation, 0, 1),
      shadowStrength: numberInRange(source.shadowStrength, DEFAULT_BUTTON_STYLE.shadowStrength, 0, 1),
      glowStrength: numberInRange(source.glowStrength, DEFAULT_BUTTON_STYLE.glowStrength, 0, 1),
    };
  } catch {
    return DEFAULT_BUTTON_STYLE;
  }
}

function color(value: unknown, fallback: string): string {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

function numberInRange(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isFinite(value)
    ? Math.min(max, Math.max(min, value))
    : fallback;
}
`;
}

export function missingButtonRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties));
  return requiredButtonRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function buttonRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingButtonRuntimeProofProperties(proof).length === 0;
}
