import { SlotCardStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const farmSlotRuntimeStylePropertyNames = [
  "fillColor",
  "innerFillColor",
  "borderWidth",
  "borderColor",
  "lockedOverlayOpacity",
  "emptySlotOpacity",
  "mergeCandidatePulseScale",
  "monsterDisplayScale",
  "monsterVerticalOffset"
] as const;

export const requiredFarmSlotRuntimeProofProperties = [
  "fillColor",
  "innerFillColor",
  "borderWidth",
  "borderColor",
  "monsterDisplayScale",
  "monsterVerticalOffset"
] as const;

type FarmSlotRuntimeStyleProperty = typeof farmSlotRuntimeStylePropertyNames[number];

export const idleMonsterFarmFarmSlotNoopStyleDefaults: SlotCardStyleValues = {
  slotWidth: 108,
  slotHeight: 108,
  gap: 12,
  borderWidth: 3,
  cornerRadius: 10,
  fillColor: "#a4dc72",
  innerFillColor: "#bee98f",
  borderColor: "#3f8c43",
  selectedGlowStrength: 0.4,
  lockedOverlayOpacity: 0.72,
  emptySlotOpacity: 0.22,
  mergeCandidatePulseScale: 1,
  monsterDisplayScale: 1,
  monsterVerticalOffset: 0
};

export function renderFarmSlotStyleModule(values: SlotCardStyleValues): string {
  const runtimeValues: Record<FarmSlotRuntimeStyleProperty, string | number> = {
    fillColor: values.fillColor,
    innerFillColor: values.innerFillColor,
    borderWidth: values.borderWidth,
    borderColor: values.borderColor,
    lockedOverlayOpacity: values.lockedOverlayOpacity,
    emptySlotOpacity: values.emptySlotOpacity,
    mergeCandidatePulseScale: values.mergeCandidatePulseScale,
    monsterDisplayScale: values.monsterDisplayScale,
    monsterVerticalOffset: values.monsterVerticalOffset
  };

  const defaultValues = {
    slotWidth: values.slotWidth,
    slotHeight: values.slotHeight,
    gap: values.gap,
    cornerRadius: values.cornerRadius,
    selectedGlowStrength: values.selectedGlowStrength,
    ...runtimeValues
  };
  const runtimePropertyUnion = farmSlotRuntimeStylePropertyNames.map((property) => `"${property}"`).join(" | ");

  return `// Generated by Game Polish Lab. Visual style values only.
export interface FarmSlotStyle {
  slotWidth: number;
  slotHeight: number;
  gap: number;
  cornerRadius: number;
  selectedGlowStrength: number;
  fillColor: string;
  innerFillColor: string;
  borderWidth: number;
  borderColor: string;
  lockedOverlayOpacity: number;
  emptySlotOpacity: number;
  mergeCandidatePulseScale: number;
  monsterDisplayScale: number;
  monsterVerticalOffset: number;
}

export type FarmSlotRuntimeLiveStyle = Partial<Pick<FarmSlotStyle, ${runtimePropertyUnion}>>;

export const DEFAULT_FARM_SLOT_STYLE: FarmSlotStyle = ${JSON.stringify(defaultValues, null, 2)};

export const FARM_SLOT_STYLE: FarmSlotStyle = { ...DEFAULT_FARM_SLOT_STYLE };

const LIVE_STYLE_PATH = '/.game-polish-lab/live-style/farm-slot.json';
const LIVE_POLL_INTERVAL_MS = 300;

let lastLivePayload = '';
let lastLivePollAt = 0;
let livePollInFlight = false;

export async function pollFarmSlotLiveStyle(now = Date.now()): Promise<boolean> {
  const env = (import.meta as unknown as { env?: { DEV?: boolean } }).env;
  if (!env?.DEV || typeof fetch !== 'function') {
    return false;
  }
  if (livePollInFlight || now - lastLivePollAt < LIVE_POLL_INTERVAL_MS) {
    return false;
  }

  livePollInFlight = true;
  lastLivePollAt = now;
  try {
    const response = await fetch(LIVE_STYLE_PATH, { cache: 'no-store' });
    if (response.status === 404) {
      return applyFarmSlotStylePayload('');
    }
    if (!response.ok) {
      return false;
    }
    return applyFarmSlotStylePayload(await response.text());
  } catch {
    return false;
  } finally {
    livePollInFlight = false;
  }
}

function applyFarmSlotStylePayload(payload: string): boolean {
  if (payload === lastLivePayload) {
    return false;
  }
  lastLivePayload = payload;
  const next = payload ? normalizeLiveFarmSlotStyle(payload) : DEFAULT_FARM_SLOT_STYLE;
  const before = JSON.stringify(FARM_SLOT_STYLE);
  Object.assign(FARM_SLOT_STYLE, next);
  return JSON.stringify(FARM_SLOT_STYLE) !== before;
}

function normalizeLiveFarmSlotStyle(payload: string): FarmSlotStyle {
  try {
    const parsed = JSON.parse(payload) as { values?: unknown };
    const source = parsed && typeof parsed === 'object' && parsed.values && typeof parsed.values === 'object'
      ? parsed.values as Record<string, unknown>
      : parsed as Record<string, unknown>;
    return {
      ...DEFAULT_FARM_SLOT_STYLE,
      fillColor: color(source.fillColor, DEFAULT_FARM_SLOT_STYLE.fillColor),
      innerFillColor: color(source.innerFillColor, DEFAULT_FARM_SLOT_STYLE.innerFillColor),
      borderColor: color(source.borderColor, DEFAULT_FARM_SLOT_STYLE.borderColor),
      borderWidth: numberInRange(source.borderWidth, DEFAULT_FARM_SLOT_STYLE.borderWidth, 0, 10),
      emptySlotOpacity: numberInRange(source.emptySlotOpacity, DEFAULT_FARM_SLOT_STYLE.emptySlotOpacity, 0, 1),
      lockedOverlayOpacity: numberInRange(source.lockedOverlayOpacity, DEFAULT_FARM_SLOT_STYLE.lockedOverlayOpacity, 0, 1),
      monsterDisplayScale: numberInRange(source.monsterDisplayScale, DEFAULT_FARM_SLOT_STYLE.monsterDisplayScale, 0.55, 1.35),
      monsterVerticalOffset: numberInRange(source.monsterVerticalOffset, DEFAULT_FARM_SLOT_STYLE.monsterVerticalOffset, -28, 28),
      mergeCandidatePulseScale: numberInRange(source.mergeCandidatePulseScale, DEFAULT_FARM_SLOT_STYLE.mergeCandidatePulseScale, 1, 1.28),
    };
  } catch {
    return DEFAULT_FARM_SLOT_STYLE;
  }
}

function color(value: unknown, fallback: string): string {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

function numberInRange(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isFinite(value)
    ? Math.min(max, Math.max(min, value))
    : fallback;
}
`;
}

export function extractFarmSlotStyleValuesFromModule(text: string | undefined, fallback: SlotCardStyleValues = idleMonsterFarmFarmSlotNoopStyleDefaults): SlotCardStyleValues {
  return extractFarmSlotStyleValuesFromModuleIfPresent(text, fallback) ?? fallback;
}

export function extractFarmSlotStyleValuesFromModuleIfPresent(text: string | undefined, fallback: SlotCardStyleValues = idleMonsterFarmFarmSlotNoopStyleDefaults): SlotCardStyleValues | undefined {
  if (!text) {
    return undefined;
  }
  const match = text.match(/(?:DEFAULT_FARM_SLOT_STYLE|FARM_SLOT_STYLE)\s*:\s*FarmSlotStyle\s*=\s*(\{[\s\S]*?\})\s*;/);
  if (!match) {
    return undefined;
  }
  try {
    const parsed = JSON.parse(match[1]) as Partial<SlotCardStyleValues>;
    return {
      slotWidth: numberOr(parsed.slotWidth, fallback.slotWidth),
      slotHeight: numberOr(parsed.slotHeight, fallback.slotHeight),
      gap: numberOr(parsed.gap, fallback.gap),
      borderWidth: numberOr(parsed.borderWidth, fallback.borderWidth),
      cornerRadius: numberOr(parsed.cornerRadius, fallback.cornerRadius),
      fillColor: colorOr(parsed.fillColor, fallback.fillColor),
      innerFillColor: colorOr(parsed.innerFillColor, colorOr(parsed.fillColor, fallback.innerFillColor)),
      borderColor: colorOr(parsed.borderColor, fallback.borderColor),
      selectedGlowStrength: numberOr(parsed.selectedGlowStrength, fallback.selectedGlowStrength),
      lockedOverlayOpacity: numberOr(parsed.lockedOverlayOpacity, fallback.lockedOverlayOpacity),
      emptySlotOpacity: numberOr(parsed.emptySlotOpacity, fallback.emptySlotOpacity),
      mergeCandidatePulseScale: numberOr(parsed.mergeCandidatePulseScale, fallback.mergeCandidatePulseScale),
      monsterDisplayScale: numberOr(parsed.monsterDisplayScale, fallback.monsterDisplayScale),
      monsterVerticalOffset: numberOr(parsed.monsterVerticalOffset, fallback.monsterVerticalOffset)
    };
  } catch {
    return undefined;
  }
}

export function extractFarmSlotStyleValuesFromSourceText(text: string | undefined, fallback: SlotCardStyleValues = idleMonsterFarmFarmSlotNoopStyleDefaults): SlotCardStyleValues | undefined {
  if (!text) {
    return undefined;
  }

  const fillColor = extractThemeColor(text, "slot");
  const innerFillColor = extractThemeColor(text, "slotInner") ?? fillColor;
  const borderColor = extractThemeColor(text, "slotBorder");
  const borderWidth = extractBorderWidth(text);
  if (!fillColor && !innerFillColor && !borderColor && borderWidth === undefined) {
    return undefined;
  }

  return {
    ...fallback,
    fillColor: fillColor ?? fallback.fillColor,
    innerFillColor: innerFillColor ?? fallback.innerFillColor,
    borderColor: borderColor ?? fallback.borderColor,
    borderWidth: borderWidth ?? fallback.borderWidth
  };
}

function extractThemeColor(text: string, propertyName: string): string | undefined {
  const match = text.match(new RegExp(`\\b${propertyName}\\s*:\\s*(0x[0-9a-fA-F]{6}|#[0-9a-fA-F]{6}|["']#[0-9a-fA-F]{6}["'])`));
  if (!match) {
    return undefined;
  }
  return normalizeSourceColor(match[1]);
}

function extractBorderWidth(text: string): number | undefined {
  const constMatch = text.match(/\bconst\s+borderWidth\s*=\s*(\d+(?:\.\d+)?)\s*;/);
  if (constMatch) {
    return Number(constMatch[1]);
  }
  const strokeMatch = text.match(/\.setStrokeStyle\s*\(\s*(\d+(?:\.\d+)?)/);
  return strokeMatch ? Number(strokeMatch[1]) : undefined;
}

function normalizeSourceColor(value: string): string | undefined {
  const cleaned = value.replace(/^["']|["']$/g, "");
  if (/^#[0-9a-f]{6}$/i.test(cleaned)) {
    return cleaned.toLowerCase();
  }
  if (/^0x[0-9a-f]{6}$/i.test(cleaned)) {
    return `#${cleaned.slice(2).toLowerCase()}`;
  }
  return undefined;
}

function numberOr(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function colorOr(value: unknown, fallback: string): string {
  return typeof value === "string" && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

export function matchedFarmSlotRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  return Array.from(new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties))).sort();
}

export function missingFarmSlotRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set(matchedFarmSlotRuntimeProofProperties(proof));
  return requiredFarmSlotRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function farmSlotRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingFarmSlotRuntimeProofProperties(proof).length === 0;
}
