import { SlotCardStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const farmSlotRuntimeStylePropertyNames = [
  "slotWidth",
  "slotHeight",
  "fillColor",
  "borderWidth",
  "borderColor",
  "lockedOverlayOpacity",
  "emptySlotOpacity",
  "mergeCandidatePulseScale",
  "monsterDisplayScale",
  "monsterVerticalOffset"
] as const;

export const requiredFarmSlotRuntimeProofProperties = [
  "slotWidth",
  "slotHeight",
  "fillColor",
  "borderWidth",
  "borderColor",
  "monsterDisplayScale",
  "monsterVerticalOffset"
] as const;

type FarmSlotRuntimeStyleProperty = typeof farmSlotRuntimeStylePropertyNames[number];

export function renderFarmSlotStyleModule(values: SlotCardStyleValues): string {
  const runtimeValues: Record<FarmSlotRuntimeStyleProperty, string | number> = {
    slotWidth: values.slotWidth,
    slotHeight: values.slotHeight,
    fillColor: values.fillColor,
    borderWidth: values.borderWidth,
    borderColor: values.borderColor,
    lockedOverlayOpacity: values.lockedOverlayOpacity,
    emptySlotOpacity: values.emptySlotOpacity,
    mergeCandidatePulseScale: values.mergeCandidatePulseScale,
    monsterDisplayScale: values.monsterDisplayScale,
    monsterVerticalOffset: values.monsterVerticalOffset
  };

  return `// Generated by Game Polish Lab. Visual style values only.
export interface FarmSlotStyle {
  slotWidth: number;
  slotHeight: number;
  fillColor: string;
  borderWidth: number;
  borderColor: string;
  lockedOverlayOpacity: number;
  emptySlotOpacity: number;
  mergeCandidatePulseScale: number;
  monsterDisplayScale: number;
  monsterVerticalOffset: number;
}

export const FARM_SLOT_STYLE: FarmSlotStyle = ${JSON.stringify(runtimeValues, null, 2)};
`;
}

export function matchedFarmSlotRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  return Array.from(new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties))).sort();
}

export function missingFarmSlotRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set(matchedFarmSlotRuntimeProofProperties(proof));
  return requiredFarmSlotRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function farmSlotRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingFarmSlotRuntimeProofProperties(proof).length === 0;
}
