import { PanelStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const panelRuntimeStylePropertyNames = [
  "fillColor",
  "fillOpacity",
  "borderColor",
  "borderWidth",
  "cornerRadius",
  "headerAccentColor",
  "headerAccentHeight",
  "padding",
  "contentGap",
  "dividerColor",
  "dividerOpacity",
  "dividerThickness",
  "shadowStrength",
  "glowStrength",
  "titleTextSize",
  "bodyTextSize",
  "disabledOpacity"
] as const;

export const requiredPanelRuntimeProofProperties = [
  "fillColor",
  "borderColor",
  "padding"
] as const;

export function renderPanelStyleModule(values: PanelStyleValues): string {
  return `// Generated by Game Polish Lab. Visual style values only.
export interface PanelStyle {
  fillColor: string;
  fillOpacity: number;
  borderColor: string;
  borderWidth: number;
  cornerRadius: number;
  headerAccentColor: string;
  headerAccentHeight: number;
  padding: number;
  contentGap: number;
  dividerColor: string;
  dividerOpacity: number;
  dividerThickness: number;
  shadowStrength: number;
  glowStrength: number;
  titleTextSize: number;
  bodyTextSize: number;
  disabledOpacity: number;
}

export const PANEL_STYLE: PanelStyle = ${JSON.stringify(values, null, 2)};
`;
}

export function missingPanelRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties));
  return requiredPanelRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function panelRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingPanelRuntimeProofProperties(proof).length === 0;
}
