import { PanelStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const panelRuntimeStylePropertyNames = [
  "fillColor",
  "fillOpacity",
  "borderColor",
  "borderWidth",
  "cornerRadius",
  "headerAccentColor",
  "headerAccentHeight",
  "padding",
  "contentGap",
  "dividerColor",
  "dividerOpacity",
  "dividerThickness",
  "shadowStrength",
  "glowStrength",
  "titleTextSize",
  "bodyTextSize",
  "disabledOpacity"
] as const;

export const requiredPanelRuntimeProofProperties = [
  "fillColor",
  "borderColor"
] as const;

export function renderPanelStyleModule(values: PanelStyleValues): string {
  const runtimePropertyUnion = panelRuntimeStylePropertyNames.map((property) => `"${property}"`).join(" | ");
  return `// Generated by Game Polish Lab. Visual style values only.
export interface PanelStyle {
  fillColor: string;
  fillOpacity: number;
  borderColor: string;
  borderWidth: number;
  cornerRadius: number;
  headerAccentColor: string;
  headerAccentHeight: number;
  padding: number;
  contentGap: number;
  dividerColor: string;
  dividerOpacity: number;
  dividerThickness: number;
  shadowStrength: number;
  glowStrength: number;
  titleTextSize: number;
  bodyTextSize: number;
  disabledOpacity: number;
}

export type PanelRuntimeLiveStyle = Partial<Pick<PanelStyle, ${runtimePropertyUnion}>>;

export const DEFAULT_PANEL_STYLE: PanelStyle = ${JSON.stringify(values, null, 2)};

export const PANEL_STYLE: PanelStyle = { ...DEFAULT_PANEL_STYLE };

const LIVE_STYLE_PATH = '/.game-polish-lab/live-style/panel.json';
const LIVE_POLL_INTERVAL_MS = 300;

let lastLivePayload = '';
let lastLivePollAt = 0;
let livePollInFlight = false;

export async function pollPanelLiveStyle(now = Date.now()): Promise<boolean> {
  const env = (import.meta as unknown as { env?: { DEV?: boolean } }).env;
  if (!env?.DEV || typeof fetch !== 'function') {
    return false;
  }
  if (livePollInFlight || now - lastLivePollAt < LIVE_POLL_INTERVAL_MS) {
    return false;
  }

  livePollInFlight = true;
  lastLivePollAt = now;
  try {
    const response = await fetch(LIVE_STYLE_PATH, { cache: 'no-store' });
    if (response.status === 404) {
      return applyPanelStylePayload('');
    }
    if (!response.ok) {
      return false;
    }
    return applyPanelStylePayload(await response.text());
  } catch {
    return false;
  } finally {
    livePollInFlight = false;
  }
}

function applyPanelStylePayload(payload: string): boolean {
  if (payload === lastLivePayload) {
    return false;
  }
  lastLivePayload = payload;
  const next = payload ? normalizeLivePanelStyle(payload) : DEFAULT_PANEL_STYLE;
  const before = JSON.stringify(PANEL_STYLE);
  Object.assign(PANEL_STYLE, next);
  return JSON.stringify(PANEL_STYLE) !== before;
}

function normalizeLivePanelStyle(payload: string): PanelStyle {
  try {
    const parsed = JSON.parse(payload) as { values?: unknown };
    const source = parsed && typeof parsed === 'object' && parsed.values && typeof parsed.values === 'object'
      ? parsed.values as Record<string, unknown>
      : parsed as Record<string, unknown>;
    return {
      ...DEFAULT_PANEL_STYLE,
      fillColor: color(source.fillColor, DEFAULT_PANEL_STYLE.fillColor),
      fillOpacity: numberInRange(source.fillOpacity, DEFAULT_PANEL_STYLE.fillOpacity, 0, 1),
      borderColor: color(source.borderColor, DEFAULT_PANEL_STYLE.borderColor),
      borderWidth: numberInRange(source.borderWidth, DEFAULT_PANEL_STYLE.borderWidth, 0, 10),
      cornerRadius: numberInRange(source.cornerRadius, DEFAULT_PANEL_STYLE.cornerRadius, 0, 36),
      headerAccentColor: color(source.headerAccentColor, DEFAULT_PANEL_STYLE.headerAccentColor),
      headerAccentHeight: numberInRange(source.headerAccentHeight, DEFAULT_PANEL_STYLE.headerAccentHeight, 0, 32),
      padding: numberInRange(source.padding, DEFAULT_PANEL_STYLE.padding, 0, 40),
      contentGap: numberInRange(source.contentGap, DEFAULT_PANEL_STYLE.contentGap, 0, 32),
      dividerColor: color(source.dividerColor, DEFAULT_PANEL_STYLE.dividerColor),
      dividerOpacity: numberInRange(source.dividerOpacity, DEFAULT_PANEL_STYLE.dividerOpacity, 0, 1),
      dividerThickness: numberInRange(source.dividerThickness, DEFAULT_PANEL_STYLE.dividerThickness, 0, 8),
      shadowStrength: numberInRange(source.shadowStrength, DEFAULT_PANEL_STYLE.shadowStrength, 0, 1),
      glowStrength: numberInRange(source.glowStrength, DEFAULT_PANEL_STYLE.glowStrength, 0, 1),
      titleTextSize: numberInRange(source.titleTextSize, DEFAULT_PANEL_STYLE.titleTextSize, 10, 40),
      bodyTextSize: numberInRange(source.bodyTextSize, DEFAULT_PANEL_STYLE.bodyTextSize, 8, 30),
      disabledOpacity: numberInRange(source.disabledOpacity, DEFAULT_PANEL_STYLE.disabledOpacity, 0, 1),
    };
  } catch {
    return DEFAULT_PANEL_STYLE;
  }
}

function color(value: unknown, fallback: string): string {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

function numberInRange(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isFinite(value)
    ? Math.min(max, Math.max(min, value))
    : fallback;
}
`;
}

export function missingPanelRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties));
  return requiredPanelRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function panelRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingPanelRuntimeProofProperties(proof).length === 0;
}
