import { RewardToastStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const rewardToastRuntimeStylePropertyNames = [
  "durationMs",
  "riseDistance",
  "startScale",
  "peakScale",
  "endScale",
  "bounceStrength",
  "fadeInMs",
  "fadeOutMs",
  "sparkleCount",
  "sparkleScale",
  "textSize",
  "iconScale",
  "toastFillColor",
  "toastFillOpacity",
  "toastBorderColor",
  "toastBorderWidth",
  "cornerRadius",
  "shadowStrength",
  "glowStrength"
] as const;

export const requiredRewardToastRuntimeProofProperties = [
  "durationMs",
  "riseDistance",
  "textSize"
] as const;

export function renderRewardToastStyleModule(values: RewardToastStyleValues): string {
  return `// Generated by Game Polish Lab. Visual style values only.
export interface RewardToastStyle {
  durationMs: number;
  riseDistance: number;
  startScale: number;
  peakScale: number;
  endScale: number;
  bounceStrength: number;
  fadeInMs: number;
  fadeOutMs: number;
  sparkleCount: number;
  sparkleScale: number;
  textSize: number;
  iconScale: number;
  toastFillColor: string;
  toastFillOpacity: number;
  toastBorderColor: string;
  toastBorderWidth: number;
  cornerRadius: number;
  shadowStrength: number;
  glowStrength: number;
}

export const REWARD_TOAST_STYLE: RewardToastStyle = ${JSON.stringify(values, null, 2)};
`;
}

export function missingRewardToastRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties));
  return requiredRewardToastRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function rewardToastRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingRewardToastRuntimeProofProperties(proof).length === 0;
}
