import { RewardToastStyleValues } from "../types/visualSurface";
import { runtimeProofAllowsDirectApply, VisualRuntimeConnectionProof } from "./visualRuntimeConnectionProof";

export const rewardToastRuntimeStylePropertyNames = [
  "durationMs",
  "riseDistance",
  "startScale",
  "peakScale",
  "endScale",
  "bounceStrength",
  "fadeInMs",
  "fadeOutMs",
  "sparkleCount",
  "sparkleScale",
  "textSize",
  "iconScale",
  "toastFillColor",
  "toastFillOpacity",
  "toastBorderColor",
  "toastBorderWidth",
  "cornerRadius",
  "shadowStrength",
  "glowStrength"
] as const;

export const requiredRewardToastRuntimeProofProperties = [
  "durationMs",
  "riseDistance",
  "textSize"
] as const;

export function renderRewardToastStyleModule(values: RewardToastStyleValues): string {
  const runtimePropertyUnion = rewardToastRuntimeStylePropertyNames.map((property) => `"${property}"`).join(" | ");
  return `// Generated by Game Polish Lab. Visual style values only.
export interface RewardToastStyle {
  durationMs: number;
  riseDistance: number;
  startScale: number;
  peakScale: number;
  endScale: number;
  bounceStrength: number;
  fadeInMs: number;
  fadeOutMs: number;
  sparkleCount: number;
  sparkleScale: number;
  textSize: number;
  iconScale: number;
  toastFillColor: string;
  toastFillOpacity: number;
  toastBorderColor: string;
  toastBorderWidth: number;
  cornerRadius: number;
  shadowStrength: number;
  glowStrength: number;
}

export type RewardToastRuntimeLiveStyle = Partial<Pick<RewardToastStyle, ${runtimePropertyUnion}>>;

export const DEFAULT_REWARD_TOAST_STYLE: RewardToastStyle = ${JSON.stringify(values, null, 2)};

export const REWARD_TOAST_STYLE: RewardToastStyle = { ...DEFAULT_REWARD_TOAST_STYLE };

const LIVE_STYLE_PATH = '/.game-polish-lab/live-style/reward-toast.json';
const LIVE_POLL_INTERVAL_MS = 300;

let lastLivePayload = '';
let lastLivePollAt = 0;
let livePollInFlight = false;

export async function pollRewardToastLiveStyle(now = Date.now()): Promise<boolean> {
  const env = (import.meta as unknown as { env?: { DEV?: boolean } }).env;
  if (!env?.DEV || typeof fetch !== 'function') {
    return false;
  }
  if (livePollInFlight || now - lastLivePollAt < LIVE_POLL_INTERVAL_MS) {
    return false;
  }

  livePollInFlight = true;
  lastLivePollAt = now;
  try {
    const response = await fetch(LIVE_STYLE_PATH, { cache: 'no-store' });
    if (response.status === 404) {
      return applyRewardToastStylePayload('');
    }
    if (!response.ok) {
      return false;
    }
    return applyRewardToastStylePayload(await response.text());
  } catch {
    return false;
  } finally {
    livePollInFlight = false;
  }
}

function applyRewardToastStylePayload(payload: string): boolean {
  if (payload === lastLivePayload) {
    return false;
  }
  lastLivePayload = payload;
  const next = payload ? normalizeLiveRewardToastStyle(payload) : DEFAULT_REWARD_TOAST_STYLE;
  const before = JSON.stringify(REWARD_TOAST_STYLE);
  Object.assign(REWARD_TOAST_STYLE, next);
  return JSON.stringify(REWARD_TOAST_STYLE) !== before;
}

function normalizeLiveRewardToastStyle(payload: string): RewardToastStyle {
  try {
    const parsed = JSON.parse(payload) as { values?: unknown };
    const source = parsed && typeof parsed === 'object' && parsed.values && typeof parsed.values === 'object'
      ? parsed.values as Record<string, unknown>
      : parsed as Record<string, unknown>;
    return {
      ...DEFAULT_REWARD_TOAST_STYLE,
      durationMs: numberInRange(source.durationMs, DEFAULT_REWARD_TOAST_STYLE.durationMs, 120, 5000),
      riseDistance: numberInRange(source.riseDistance, DEFAULT_REWARD_TOAST_STYLE.riseDistance, 0, 160),
      startScale: numberInRange(source.startScale, DEFAULT_REWARD_TOAST_STYLE.startScale, 0.4, 2),
      peakScale: numberInRange(source.peakScale, DEFAULT_REWARD_TOAST_STYLE.peakScale, 0.4, 2.4),
      endScale: numberInRange(source.endScale, DEFAULT_REWARD_TOAST_STYLE.endScale, 0.2, 2),
      bounceStrength: numberInRange(source.bounceStrength, DEFAULT_REWARD_TOAST_STYLE.bounceStrength, 0, 1),
      fadeInMs: numberInRange(source.fadeInMs, DEFAULT_REWARD_TOAST_STYLE.fadeInMs, 0, 1500),
      fadeOutMs: numberInRange(source.fadeOutMs, DEFAULT_REWARD_TOAST_STYLE.fadeOutMs, 0, 1500),
      sparkleCount: Math.round(numberInRange(source.sparkleCount, DEFAULT_REWARD_TOAST_STYLE.sparkleCount, 0, 16)),
      sparkleScale: numberInRange(source.sparkleScale, DEFAULT_REWARD_TOAST_STYLE.sparkleScale, 0.2, 2),
      textSize: numberInRange(source.textSize, DEFAULT_REWARD_TOAST_STYLE.textSize, 8, 36),
      iconScale: numberInRange(source.iconScale, DEFAULT_REWARD_TOAST_STYLE.iconScale, 0.3, 2),
      toastFillColor: color(source.toastFillColor, DEFAULT_REWARD_TOAST_STYLE.toastFillColor),
      toastFillOpacity: numberInRange(source.toastFillOpacity, DEFAULT_REWARD_TOAST_STYLE.toastFillOpacity, 0, 1),
      toastBorderColor: color(source.toastBorderColor, DEFAULT_REWARD_TOAST_STYLE.toastBorderColor),
      toastBorderWidth: numberInRange(source.toastBorderWidth, DEFAULT_REWARD_TOAST_STYLE.toastBorderWidth, 0, 8),
      cornerRadius: numberInRange(source.cornerRadius, DEFAULT_REWARD_TOAST_STYLE.cornerRadius, 0, 32),
      shadowStrength: numberInRange(source.shadowStrength, DEFAULT_REWARD_TOAST_STYLE.shadowStrength, 0, 1),
      glowStrength: numberInRange(source.glowStrength, DEFAULT_REWARD_TOAST_STYLE.glowStrength, 0, 1),
    };
  } catch {
    return DEFAULT_REWARD_TOAST_STYLE;
  }
}

function color(value: unknown, fallback: string): string {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

function numberInRange(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isFinite(value)
    ? Math.min(max, Math.max(min, value))
    : fallback;
}
`;
}

export function missingRewardToastRuntimeProofProperties(proof: VisualRuntimeConnectionProof | undefined): string[] {
  const matched = new Set((proof?.evidenceFiles ?? []).flatMap((file) => file.matchedProperties));
  return requiredRewardToastRuntimeProofProperties.filter((property) => !matched.has(property));
}

export function rewardToastRuntimeProofIncludesSetupMinimum(proof: VisualRuntimeConnectionProof | undefined): boolean {
  return runtimeProofAllowsDirectApply(proof) && missingRewardToastRuntimeProofProperties(proof).length === 0;
}
