import * as vscode from "vscode";

import { ProjectTypeSuggestion } from "./projectType";
import { ensureDirectory, labUri, readTextFile, writeTextFile } from "./workspace";
import { ProjectProfile } from "../types/profile";

export interface TrialReportEntry {
  uri: vscode.Uri;
  fileName: string;
  modifiedTime: number;
}

export interface TrialReportInput {
  workspacePath: string;
  profile: ProjectProfile;
  suggestion: ProjectTypeSuggestion;
  trialTarget: string;
  blocker: string;
  projectStatus: string;
  artifactUsed: string;
}

export async function getNextNumberedFilename(folder: vscode.WorkspaceFolder, subfolder: string, suffix: string): Promise<string> {
  const targetFolder = labUri(folder, subfolder);
  let highest = 0;

  try {
    const entries = await vscode.workspace.fs.readDirectory(targetFolder);
    for (const [name] of entries) {
      const match = /^(\d+)-/.exec(name);
      if (match) {
        highest = Math.max(highest, Number(match[1]));
      }
    }
  } catch {
    // Missing folders start at 1.
  }

  return `${String(highest + 1).padStart(3, "0")}-${suffix}`;
}

export async function listTrialReports(folder: vscode.WorkspaceFolder): Promise<TrialReportEntry[]> {
  const trialsFolder = labUri(folder, "trials");
  let entries: [string, vscode.FileType][];

  try {
    entries = await vscode.workspace.fs.readDirectory(trialsFolder);
  } catch {
    return [];
  }

  const reports = await Promise.all(entries
    .filter(([name, type]) => type === vscode.FileType.File && name.endsWith(".md"))
    .map(async ([name]) => {
      const uri = labUri(folder, "trials", name);
      const stat = await vscode.workspace.fs.stat(uri);
      return {
        uri,
        fileName: name,
        modifiedTime: stat.mtime
      };
    }));

  return reports.sort((a, b) => b.modifiedTime - a.modifiedTime || b.fileName.localeCompare(a.fileName));
}

export async function findLatestTrialReport(folder: vscode.WorkspaceFolder): Promise<TrialReportEntry | undefined> {
  return (await listTrialReports(folder))[0];
}

export async function appendToTrialReport(uri: vscode.Uri, markdown: string): Promise<void> {
  const existing = await readTextFile(uri);
  const separator = existing.endsWith("\n") ? "\n" : "\n\n";
  await writeTextFile(uri, `${existing}${separator}${markdown.trim()}\n`);
}

export async function createTrialReport(folder: vscode.WorkspaceFolder, input: TrialReportInput): Promise<vscode.Uri> {
  await ensureDirectory(labUri(folder, "trials"));
  const fileName = await getNextNumberedFilename(folder, "trials", "real-project-trial.md");
  const uri = labUri(folder, "trials", fileName);
  await writeTextFile(uri, buildTrialReportMarkdown(input));
  return uri;
}

export function buildTrialReportMarkdown(input: TrialReportInput): string {
  return `# Game Polish Lab - Real Project Trial

## Project

* Workspace: ${input.workspacePath}
* Engine: ${input.profile.engine}
* Style: ${input.profile.style}
* Profile project type: ${input.profile.projectType}
* Suggested project type: ${input.suggestion.suggestedProjectType}
* Project status: ${input.projectStatus}

## Trial Target

* Target: ${input.trialTarget}
* Blocker: ${input.blocker}
* Artifact used: ${input.artifactUsed}

## Before Notes

* What feels wrong:
* What screen/system is affected:
* Why this blocks shipping:

## Generated Artifacts

* Audit report:
* Task file:
* Kit folder:
* Config file:
* Codex prompt:
* Scope check:

## Codex Plan Review

* Planned files:
* Approved files:
* Rejected files:
* Notes:

## After Test

* Result: better / worse / same / not tested
* What improved:
* What got worse:
* What still feels wrong:
* Did config tuning help:

## Scope Guard Result

* Allowed changes:
* Suspicious changes:
* Forbidden changes:
* Notes:

## Extension Feedback

* What Game Polish Lab did well:
* What was confusing:
* Missing preset/kit:
* Prompt problem:
* Audit problem:
* Next extension improvement:

## Decision

* keep_patch
* revert_patch
* tune_more
* create_another_task
* archive_project_for_now

Generated by Game Polish Lab v0.2.1
`;
}
