import * as fs from "fs";
import * as path from "path";

import { createVisualTextRollbackSnapshot } from "./visualRollback";
import { checkVisualScopeGuard, normalizeVisualScopePath, visualScopeGuardWarnings } from "./visualScopeGuard";

export const polishDevOverlayRelativeDir = ".game-polish-lab/dev-overlay";
export const polishDevOverlayScriptRelativePath = `${polishDevOverlayRelativeDir}/polish-dev-overlay.js`;
export const polishDevOverlayStyleRelativePath = `${polishDevOverlayRelativeDir}/polish-dev-overlay.css`;
export const polishDevOverlayReadmeRelativePath = `${polishDevOverlayRelativeDir}/README.md`;
export const polishDevOverlayManifestRelativePath = `${polishDevOverlayRelativeDir}/manifest.json`;
export const polishDevOverlayGeneratedMarker = "Generated by Game Polish Lab optional dev overlay spike";

export interface PolishDevOverlayFile {
  relativePath: string;
  text: string;
}

export interface PolishDevOverlayPlan {
  planId: "optional-dev-overlay-spike";
  executable: boolean;
  writePaths: string[];
  scopeGuardResult: ReturnType<typeof checkVisualScopeGuard>;
  warnings: string[];
  blockingReasons: string[];
  files: PolishDevOverlayFile[];
}

export interface PolishDevOverlayInstallResult {
  ok: boolean;
  changedFiles: string[];
  rollbackPaths: string[];
  errors: string[];
  warnings: string[];
}

export interface PolishDevOverlayStatus {
  exists: boolean;
  generated: boolean;
  path: string;
  fileCount: number;
  generatedFileCount: number;
  files: Array<{
    relativePath: string;
    exists: boolean;
    generated: boolean;
  }>;
  warnings: string[];
}

export interface CreatePolishDevOverlaySpikeResult {
  approved: boolean;
  plan?: PolishDevOverlayPlan;
  result?: PolishDevOverlayInstallResult;
}

export function devOverlayWritePaths(): string[] {
  return [
    polishDevOverlayScriptRelativePath,
    polishDevOverlayStyleRelativePath,
    polishDevOverlayReadmeRelativePath,
    polishDevOverlayManifestRelativePath
  ];
}

export function buildPolishDevOverlayInstallPlan(input: { candidatePaths?: string[]; generatedAt?: Date } = {}): PolishDevOverlayPlan {
  const files = buildPolishDevOverlayFiles(input.generatedAt ?? new Date());
  const writePaths = files.map((file) => file.relativePath);
  const candidatePaths = Array.from(new Set((input.candidatePaths ?? writePaths).map(normalizeVisualScopePath).filter(Boolean))).sort();
  const scopeGuardResult = checkVisualScopeGuard({
    operationType: "dev_overlay_install",
    adapterId: "generic_phaser",
    candidatePaths: candidatePaths.length > 0 ? candidatePaths : ["unknown"]
  });
  const warnings = visualScopeGuardWarnings(scopeGuardResult);
  const blockingReasons: string[] = [];

  for (const candidatePath of candidatePaths) {
    if (!isSafeDevOverlayPath(candidatePath)) {
      blockingReasons.push(`Dev overlay install is limited to ${polishDevOverlayRelativeDir}/. Remove this path from the plan: ${candidatePath}`);
    }
  }
  if (scopeGuardResult.recommendedAction === "block") {
    blockingReasons.push(`Scope guard blocked the dev overlay plan. Forbidden paths: ${scopeGuardResult.classifiedFiles.filter((file) => file.classification === "forbidden").map((file) => file.path).join(", ") || "none listed"}.`);
  }
  if (scopeGuardResult.recommendedAction === "warn") {
    blockingReasons.push(`Scope guard found suspicious or unknown paths. Dev overlay generation only accepts generated files under ${polishDevOverlayRelativeDir}/.`);
  }

  return {
    planId: "optional-dev-overlay-spike",
    executable: blockingReasons.length === 0 && candidatePaths.length > 0,
    writePaths,
    scopeGuardResult,
    warnings,
    blockingReasons,
    files
  };
}

export function createOptionalPolishDevOverlaySpike(workspaceRoot: string, approved: boolean, now: Date = new Date()): CreatePolishDevOverlaySpikeResult {
  if (!approved) {
    return { approved: false };
  }
  const plan = buildPolishDevOverlayInstallPlan({ generatedAt: now });
  return {
    approved: true,
    plan,
    result: executePolishDevOverlayInstallPlan(workspaceRoot, plan, now)
  };
}

export function executePolishDevOverlayInstallPlan(workspaceRoot: string, plan: PolishDevOverlayPlan, now: Date = new Date()): PolishDevOverlayInstallResult {
  if (!plan.executable) {
    return {
      ok: false,
      changedFiles: [],
      rollbackPaths: [],
      errors: plan.blockingReasons,
      warnings: plan.warnings
    };
  }

  const plannedWritePaths = new Set(plan.writePaths);
  const changedFiles: string[] = [];
  const rollbackPaths: string[] = [];
  const errors: string[] = [];

  for (const file of plan.files) {
    const relativePath = normalizeVisualScopePath(file.relativePath);
    if (!plannedWritePaths.has(relativePath)) {
      errors.push(`Write path was not in the approved dev overlay plan: ${relativePath}`);
      continue;
    }
    if (!isSafeDevOverlayPath(relativePath)) {
      errors.push(`Dev overlay generation can only write ${polishDevOverlayRelativeDir}/ files: ${relativePath}`);
      continue;
    }
    const resolvedPath = resolveWorkspacePath(workspaceRoot, relativePath);
    if (!resolvedPath) {
      errors.push(`Write path does not resolve inside workspace: ${relativePath}`);
      continue;
    }

    if (fs.existsSync(resolvedPath) && fs.statSync(resolvedPath).isFile()) {
      rollbackPaths.push(createVisualTextRollbackSnapshot(workspaceRoot, relativePath, resolvedPath, now));
    }
    fs.mkdirSync(path.dirname(resolvedPath), { recursive: true });
    fs.writeFileSync(resolvedPath, file.text, "utf8");
    changedFiles.push(relativePath);
  }

  return {
    ok: errors.length === 0,
    changedFiles,
    rollbackPaths,
    errors,
    warnings: plan.warnings
  };
}

export function inspectPolishDevOverlayStatus(workspaceRoot: string): PolishDevOverlayStatus {
  const files = devOverlayWritePaths().map((relativePath) => {
    const resolvedPath = resolveWorkspacePath(workspaceRoot, relativePath);
    const exists = Boolean(resolvedPath && fs.existsSync(resolvedPath) && fs.statSync(resolvedPath).isFile());
    const text = exists && resolvedPath ? fs.readFileSync(resolvedPath, "utf8") : "";
    return {
      relativePath,
      exists,
      generated: exists && text.includes(polishDevOverlayGeneratedMarker)
    };
  });
  const fileCount = files.filter((file) => file.exists).length;
  const generatedFileCount = files.filter((file) => file.generated).length;
  const warnings = files
    .filter((file) => file.exists && !file.generated)
    .map((file) => `${file.relativePath} exists but does not contain the Game Polish Lab generated marker.`);
  return {
    exists: fileCount > 0,
    generated: fileCount > 0 && fileCount === generatedFileCount,
    path: polishDevOverlayRelativeDir,
    fileCount,
    generatedFileCount,
    files,
    warnings
  };
}

export function buildPolishDevOverlayFiles(generatedAt: Date = new Date()): PolishDevOverlayFile[] {
  return [
    { relativePath: polishDevOverlayScriptRelativePath, text: renderPolishDevOverlayScript() },
    { relativePath: polishDevOverlayStyleRelativePath, text: renderPolishDevOverlayStyle() },
    { relativePath: polishDevOverlayReadmeRelativePath, text: renderPolishDevOverlayReadme() },
    { relativePath: polishDevOverlayManifestRelativePath, text: renderPolishDevOverlayManifest(generatedAt) }
  ];
}

function renderPolishDevOverlayScript(): string {
  return `// ${polishDevOverlayGeneratedMarker}
// Experimental developer-only runtime. It is inert unless the page URL has ?polish=1 or &polish=1.
(function () {
  "use strict";

  const params = new URLSearchParams(window.location.search);
  if (params.get("polish") !== "1") {
    return;
  }

  const configPayload = window.__GAME_POLISH_LAB_CONFIG__ || window.gamePolishLabConfig || null;
  const values = {
    opacity: 1,
    scale: 1,
    radius: 8,
    borderWidth: 1,
    glowStrength: 0
  };

  function emitChange() {
    window.dispatchEvent(new CustomEvent("game-polish-lab:tune-change", {
      detail: {
        source: "game-polish-lab-dev-overlay",
        values: Object.assign({}, values)
      }
    }));
  }

  function createSlider(label, key, min, max, step) {
    const row = document.createElement("label");
    row.className = "gpl-dev-overlay-control";
    const text = document.createElement("span");
    text.textContent = label;
    const value = document.createElement("output");
    value.textContent = String(values[key]);
    const input = document.createElement("input");
    input.type = "range";
    input.min = String(min);
    input.max = String(max);
    input.step = String(step);
    input.value = String(values[key]);
    input.addEventListener("input", function () {
      values[key] = Number(input.value);
      value.textContent = input.value;
      emitChange();
    });
    row.append(text, input, value);
    return row;
  }

  function renderPayload() {
    if (!configPayload) {
      return "No config payload detected.";
    }
    try {
      return JSON.stringify(configPayload, null, 2);
    } catch {
      return String(configPayload);
    }
  }

  const panel = document.createElement("aside");
  panel.className = "gpl-dev-overlay";
  panel.setAttribute("aria-label", "Game Polish Lab Dev Overlay");
  const title = document.createElement("h2");
  title.textContent = "Game Polish Lab Dev Overlay";
  const note = document.createElement("p");
  note.textContent = "Developer-only visual tuning events. No game save writes.";
  const payload = document.createElement("pre");
  payload.textContent = renderPayload();
  panel.append(
    title,
    note,
    createSlider("Opacity", "opacity", 0.2, 1, 0.05),
    createSlider("Scale", "scale", 0.5, 2, 0.05),
    createSlider("Radius", "radius", 0, 32, 1),
    createSlider("Border", "borderWidth", 0, 8, 1),
    createSlider("Glow", "glowStrength", 0, 32, 1),
    payload
  );
  document.documentElement.classList.add("game-polish-lab-dev-overlay-enabled");
  document.body.append(panel);
  emitChange();
}());
`;
}

function renderPolishDevOverlayStyle(): string {
  return `/* ${polishDevOverlayGeneratedMarker} */
.gpl-dev-overlay {
  position: fixed;
  z-index: 2147483647;
  top: 12px;
  right: 12px;
  width: min(320px, calc(100vw - 24px));
  max-height: calc(100vh - 24px);
  overflow: auto;
  padding: 12px;
  color: #f8fafc;
  background: rgba(15, 23, 42, 0.94);
  border: 1px solid rgba(148, 163, 184, 0.55);
  border-radius: 8px;
  box-shadow: 0 12px 36px rgba(0, 0, 0, 0.35);
  font: 12px/1.4 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
.gpl-dev-overlay h2 {
  margin: 0 0 6px;
  font-size: 14px;
}
.gpl-dev-overlay p {
  margin: 0 0 10px;
  color: #cbd5e1;
}
.gpl-dev-overlay-control {
  display: grid;
  grid-template-columns: 64px 1fr 42px;
  gap: 8px;
  align-items: center;
  margin: 8px 0;
}
.gpl-dev-overlay-control input {
  width: 100%;
}
.gpl-dev-overlay pre {
  margin: 10px 0 0;
  padding: 8px;
  max-height: 160px;
  overflow: auto;
  color: #dbeafe;
  background: rgba(2, 6, 23, 0.7);
  border-radius: 6px;
  white-space: pre-wrap;
}
`;
}

function renderPolishDevOverlayReadme(): string {
  return `# Game Polish Lab Dev Overlay

${polishDevOverlayGeneratedMarker}

This overlay is optional experimental developer tooling. Game Polish Lab remains a VS Code visual polish console; the normal workflow is still choose surface, preview and tune, save config/assets, direct apply where supported, then record the result.

The overlay is inert unless the game is opened with \`?polish=1\` or \`&polish=1\`. It should be included only during local development unless you intentionally choose otherwise.

## Manual Local Integration

Add the CSS and JS manually in your local development HTML or dev-only loader:

\`\`\`html
<link rel="stylesheet" href="/.game-polish-lab/dev-overlay/polish-dev-overlay.css">
<script src="/.game-polish-lab/dev-overlay/polish-dev-overlay.js"></script>
\`\`\`

Then open the game with:

\`\`\`text
http://localhost:3000/?polish=1
\`\`\`

The script emits \`game-polish-lab:tune-change\` browser \`CustomEvent\` messages with visual-only values. It does not mutate Phaser gameplay state, persist to game save data, call network APIs, or load external CDNs.

## Optional Config Payload

To display a detected config payload, set one of these globals before loading the overlay script:

\`\`\`js
window.__GAME_POLISH_LAB_CONFIG__ = { surface: "button", values: {} };
\`\`\`

## Removal

Remove the manual CSS/JS include and delete:

\`\`\`text
${polishDevOverlayRelativeDir}/
\`\`\`

production builds should exclude these files unless the developer intentionally includes them.
`;
}

function renderPolishDevOverlayManifest(generatedAt: Date): string {
  return `${JSON.stringify({
    marker: polishDevOverlayGeneratedMarker,
    schemaVersion: "game-polish-lab/dev-overlay/v1",
    generatedAt: generatedAt.toISOString(),
    activation: "URL query param polish=1",
    files: [
      polishDevOverlayScriptRelativePath,
      polishDevOverlayStyleRelativePath,
      polishDevOverlayReadmeRelativePath
    ]
  }, null, 2)}\n`;
}

function isSafeDevOverlayPath(relativePath: string): boolean {
  const normalized = normalizeVisualScopePath(relativePath);
  return normalized.startsWith(`${polishDevOverlayRelativeDir}/`)
    && !path.isAbsolute(normalized)
    && !normalized.split("/").includes("..");
}

function resolveWorkspacePath(workspaceRoot: string, relativePath: string): string | undefined {
  const normalized = normalizeVisualScopePath(relativePath);
  if (!normalized || path.isAbsolute(normalized) || normalized.split("/").includes("..")) {
    return undefined;
  }
  const root = path.resolve(workspaceRoot);
  const resolved = path.resolve(root, ...normalized.split("/"));
  return resolved === root || resolved.startsWith(`${root}${path.sep}`) ? resolved : undefined;
}
